### ISSUE TITLE
set accessory to "no response"

### ISSUE THREAD

**Issue by timoschilling** [brutella/hc#102]
Is there a way to set a bridged accessory to a "no response" or "error" state?
For example I have a bridge for my thermostats and sometimes the bridge can't communicate with the thermostat in such a case I want to the a "no response" or "error" state.

I have a IKEA Tradfri bridge with some light bulbs and if I remove the power connection to one of the light bulbs the apple home app shows me this:
![img_1551](https://user-images.githubusercontent.com/165599/33520004-b0c11d02-d7b2-11e7-8a7f-9d72416bbb48.jpg)

**Comment by brutella** [comment]
*No Response* is shown if the Home app can't find it using Bonjour/mDNS. The [hklifx](https://github.com/brutella/hklifx) project does want you want. It publishes every light as a separate accessory. If a light becomes not available, the light is unpublished from mDNS and HomeKit apps will show *No Response*.

**Comment by timoschilling** [comment]
Ok, thanks for the hint.

But there must be a different way, the IKEA Tradfri bridge a Philips Hue like system can do that with bridged accessories.

Does someone have any idea?
