### ISSUE TITLE
Associate iid with named service/characteristic

### ISSUE THREAD

**Issue by ipstatic** [brutella/hc#104]
I hate to open an issue to ask a question but couldn't find a better way. I am trying to figure out on which service callbacks are being executed against. I have enabled debugging and can see the GETs/PUTs and what id/ad/iid they are for but I cannot figure out a way to translate that into a human form, like "CameraRTPStreamManagement.SetupEndpoints" Can anyone provide guidance?

**Comment by brutella** [comment]
The implementation of a HomeKit camera in [hkcam](https://github.com/brutella/hkcam) should help.
