### ISSUE TITLE
How to stop?

### ISSUE THREAD

**Issue by reejinbouk** [brutella/hc#109]
Hi
t.Start() is used for starting hc
which command is used for stopping hc?

Tried t.Stop() and got errors
Alse tried "<- t.Stop()" and also got errors

thank you

**Comment by aidansteele** [comment]
What errors did you get? Were they at compile time or run time?

**Comment by reejinbouk** [comment]
Got this error during runtime. Compiling is fine
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x43a1d38]

goroutine 90 [running]:
`

**Comment by brutella** [comment]
Which version of Go are you using?

**Comment by reejinbouk** [comment]
bash-3.2$ go version
go version go1.9.2 darwin/amd64

**Comment by brutella** [comment]
This should now work in v1.1.0.
