### ISSUE TITLE
Add Resource Endpoint

### ISSUE THREAD

**Issue by ipstatic** [brutella/hc#113]
I've been looking at adding IP camera support to HC and believe we are missing a requisite endpoint in order to do so: /resource. From reading the HAP documentation it appears this endpoint is only used to request an image from the IP camera (see page 245). I have tried to add an endpoint mirroring the code from Accessory and Characteristics however the endpoint never seems to get called. I wonder if there is another callback expected to be execute first?

**Comment by ipstatic** [comment]
@brutella any thoughts?

**Comment by brutella** [comment]
Take a look a the HomeKit camera implementation in [hkcam](https://github.com/brutella/hkcam).
