### ISSUE TITLE
How to process change events from a bridge

### ISSUE THREAD

**Issue by mestafin** [brutella/hc#117]
I just need some advice please

I have implemented a bridge to a KNX-based network, which is working very well for control of the KNX devices from Homekit.

What is struggle with, is to process change notifications from the bridge. When user operates a physical switch to turn a light on or off, the knx bridge gets a notification of the change in the physical device. 

What is the best way to process the event and change the value of the corresponding On characteristic of the Lightbulb service?

**Comment by timoschilling** [comment]
What kind of signal do you want to Homekit?
A toggle to button devise or a change of the state of for example a lamp?

**Comment by mestafin** [comment]
Change of state for a lamp (on off) and the brightness for lamps that have a manual dimmer

**Comment by brutella** [comment]
As described in the [readme](https://github.com/brutella/hc#callbacks), you just have to set the value of the `On` characteristics like this

```go
value := ...
accessory.Switch.On.SetValue(value)
```

By doing this, the library will automatically send a notification to all connected HomeKit clients.
