### ISSUE TITLE
Best way to handle IP address changes?

### ISSUE THREAD

**Issue by joeshaw** [brutella/hc#121]
Sometimes IP addresses change due to various network conditions (DHCP leases expire, network roaming, accessory coming online before DHCP).  On my Mac I have several HC programs start on boot, and they regularly come up before DHCP has run and bind to a Zeroconf self-assigned IP address in the 169.254.0.0/16 block.

I don't expect HomeControl to detect and handle IP address changes itself (though it would be nice...) but it's not clear to me how best to handle those changes in my program.  As far as I can tell, my only option today is to stop the IP transport, update the config's IP field, and restart it.  Is that the right way to do it, or would another approach be preferable?

**Comment by brutella** [comment]
hc publishes the IP address using mdns [here](https://github.com/brutella/hc/blob/b01f05dadb87210e72e2cd87ffa5a410846b6d4d/ip_transport.go#L154-L165). To publish IP changes we would have to remove the old service and add the new service to the mdns responder.

**Comment by brutella** [comment]
With the latest changes to [dnssd](https://github.com/brutella/dnssd), this should be handled automatically.
