### ISSUE TITLE
loose pairing

### ISSUE THREAD

**Issue by reejinbouk** [brutella/hc#122]
Hello,
After pair got too many of this messages:

INFO 2018/06/19 17:08:04 Non-admin controllers are not allowed to add pairings
INFO 2018/06/19 17:08:12 Client 8517A897-C25C-4513-89FA-F18072FB7500 is unknown

And after some days loose connection with iOS - always got no response on iOS.
I've add some log to hc/hap/pair/verify_server_controller.go and got this error here:
175 entity, err := verify.database.EntityWithName(username)

error is:
open /persist/38353137413839372d433235432d343531332d383946412d463138303732464237353030.entity: no such file or directory

Why it change file name? Client ID is the same that after pair some days ago

**Comment by brutella** [comment]
I suspect your issue is related to #119 
Are you using an ATV3 in your home?

**Comment by reejinbouk** [comment]
no

**Comment by brutella** [comment]
This should work now.
