### ISSUE TITLE
Add television support

### ISSUE THREAD

**Issue by brutella** [brutella/hc#132]
iOS 12.2 beta 1 supports new HomeKit types for television

**Comment by timoschilling** [comment]
Thanks for adding Television support. I god an basic setup working. Can you give an example how to use / configure InputSource's?

**Comment by brutella** [comment]
Take a look `func addInputSource(...)` in `_example/tv/main.go` to see how to add an input source to a television accessory.

**Comment by timoschilling** [comment]
There is no `tv` example in your `tv` branch.

**Comment by brutella** [comment]
Now it is. ;)

**Comment by timoschilling** [comment]
THX

**Comment by timoschilling** [comment]
There is an bug, I don't know if it is a bug from hc or HomeKit / Home App.
You can't add input sources to an configured / already added tv accessory.
You need to remove and readd it, to get the new input work.
