### ISSUE TITLE
No response after restarting program

### ISSUE THREAD

**Issue by radionoise** [brutella/hc#133]
Hello! I'm trying to run example from _example directory. I'm just pasting the code to my main.go file, running go get to fetch dependencies and running it.

1. Lamp switch is pairing successfully and working.

2. When I stop and restart the program the connection is gone. I can see only this in console:
`DEBUG 2019/02/07 10:04:07 Switch is off
DEBUG 2019/02/07 10:04:12 Switch is on
DEBUG 2019/02/07 10:04:17 Switch is off
DEBUG 2019/02/07 10:04:22 Switch is on
DEBUG 2019/02/07 10:04:27 Switch is off`

3. When I turn off Wi-Fi on iPhone and switch it on later, iOS successfully connects to Lamp switch resulting in this output:
`DEBUG 2019/02/07 10:04:28 192.168.10.111:50200 POST /pair-verify
DEBUG 2019/02/07 10:04:28 Create new pair verify controller
DEBUG 2019/02/07 10:04:28 ->     A: 476c5c0c3fe3da025d28c7a220511691e7f827484028de886f536b439597aa4f
DEBUG 2019/02/07 10:04:28        K: 57aeecb79132f414a50c3861c71a0167885e06297252d61b792b58c008829edb
DEBUG 2019/02/07 10:04:28        B: 9b7dd06b17df12c389281d631e83b8db3976c653ca472ecea5be1049b258a343
DEBUG 2019/02/07 10:04:28        S: c5f864546f78687ea542cc8cac69c695e68b1222941dddc3d8fa1ba7aa2f10cc
DEBUG 2019/02/07 10:04:28   Shared: 775eeb94d0f117332c4446a16e6b83f0b1d825ef0bdb04154c29b80707f3eb61
DEBUG 2019/02/07 10:04:28 <-     B: 9b7dd06b17df12c389281d631e83b8db3976c653ca472ecea5be1049b258a343
DEBUG 2019/02/07 10:04:29 192.168.10.111:50200 POST /pair-verify
DEBUG 2019/02/07 10:04:29 ->     Message: f7339488657988b574fc6eaff3b45b85175df2da806828f13f0b52edb2ef83fc565711b03d726b3e6a68ef7d98786d03b8d56ef45ebc4857f1f537cef24cc77b1280d369ed960aa0261505a313ae8bbf6a0f6943bd91475c7c1fba55723616d30f5a134a0834a141
DEBUG 2019/02/07 10:04:29 ->     MAC: 5fcf5b478e96c274354d40137c1e79c9
DEBUG 2019/02/07 10:04:29     client: B22DA38E-1640-4E1C-A7A1-54B1A6173A62
DEBUG 2019/02/07 10:04:29  signature: cd91ee1aebcd5e20dcde2edaae0ae1d67665ed94bbbe289ca2f237b75051e799bfbaeea42579f467ede4055b2ed162c6307ea4c69582fe4fb4bea873717cf70b
DEBUG 2019/02/07 10:04:29 signature is valid
DEBUG 2019/02/07 10:04:29 Setup secure session
DEBUG 2019/02/07 10:04:29 192.168.10.111:50200 GET /accessories
DEBUG 2019/02/07 10:04:29 {"accessories":[{"aid":1,"services":[{"iid":1,"type":"3E","characteristics":[{"iid":2,"type":"14","perms":["pw"],"format":"bool"},{"iid":3,"type":"20","perms":["pr"],"value":"undefined","format":"string"},{"iid":4,"type":"21","perms":["pr"],"value":"undefined","format":"string"},{"iid":5,"type":"23","perms":["pr"],"value":"Lamp","format":"string"},{"iid":6,"type":"30","perms":["pr"],"value":"undefined","format":"string"},{"iid":7,"type":"52","perms":["pr"],"value":"","format":"string"}]},{"iid":8,"type":"49","characteristics":[{"iid":9,"type":"25","perms":["pr","pw","ev"],"value":false,"format":"bool"}]}]}]}
DEBUG 2019/02/07 10:04:29 192.168.10.111:50200 PUT /characteristics
DEBUG 2019/02/07 10:04:29 {"characteristics":[{"aid":1,"iid":9,"ev":true}]}
DEBUG 2019/02/07 10:04:29 192.168.10.111:50200 PUT /characteristics
DEBUG 2019/02/07 10:04:29 {"characteristics":[{"aid":1,"iid":9,"ev":true}]}`

4. Sometimes when I create a new accessory I can't see it when trying to pair. Switching Wi-Fi off and on on iPhone fixes the problem.

The bug does not occur when testing with HomeKit Accessory Simulator.

**Comment by brutella** [comment]
I think that's a dns issue. 
Can you please enable dns debug logs with the following.

```go
import (
    dnslog "github.com/brutella/dnssd/log
)

func main() {
    …
    dnslog.Debug.Enable()
}


```

**Comment by radionoise** [comment]
I've added import statement, called dnslog.Debug.Enable() and created accessory with a new name (two old accessories are visible as available for pairing. I restarted computer, but they are still visible), paired with it, restarted the program and nothing (even after switching Wi-Fi off and on). However, I don't see any output related to dns :(

First start:
`DEBUG 2019/02/07 11:06:07 Switch is on
INFO 2019/02/07 11:06:07 Accessory address is 192.168.10.145:12345
DEBUG 2019/02/07 11:06:12 Switch is off
DEBUG 2019/02/07 11:06:17 Switch is on
DEBUG 2019/02/07 11:06:22 Switch is off
DEBUG 2019/02/07 11:06:27 Switch is on
DEBUG 2019/02/07 11:06:32 Switch is off
DEBUG 2019/02/07 11:06:37 Switch is on
DEBUG 2019/02/07 11:06:42 Switch is off
DEBUG 2019/02/07 11:06:47 Switch is on
DEBUG 2019/02/07 11:06:52 Switch is off
DEBUG 2019/02/07 11:06:57 Switch is on
DEBUG 2019/02/07 11:07:02 Switch is off
DEBUG 2019/02/07 11:07:07 Switch is on
DEBUG 2019/02/07 11:07:10 192.168.10.111:50342 POST /pair-setup
DEBUG 2019/02/07 11:07:10 Create new pair setup controller
DEBUG 2019/02/07 11:07:10 <-     B: 0c93320e758082284159b5d8273042175013351bdee64c8d17fff438acd8492144cfd6918475810a46fb18ad007578026f2602bc1d1fbad4da58dd8121d4a9a5e1ff9a8c013d4b20c8fdf36d47d2305d1f7df4382949dcb44bb1ea1ab569de480a763d7d225846b5e3734812a4f3915a3cd37682b783e5b767ff83e123c43b079013ee9ebbd62fbbcede9abb976c64bd35f69bd446395aefc06e207b6a4833e2ae818374be9e393274ef57c6cc9870366cabea98893f8cca84820a6f74cf65e9a31e766d21424ea7eec8833b5efc71f5cf80ff1d3f7ff3bbe48077c1a5caddf271fae91b6c1e027688d1435fb586f24b1e9aa3ca5938b82f981cf00ae8b1c32da43556e8ff2552b712c643199bef81ba03ad3bc28ae120de4d33fa1d440122691b38933a5e6de3fc9d957e20c3cc0c5a4c63882e53c572356489d9864645c996b447c30719ac54c8efc90dc93de2ba4a749767041cf41c4bd5ac8eba85d86c8d4fc09934b5ed5c20641702a8554766110598df1697b61ca06ed3523ad1a5868f
DEBUG 2019/02/07 11:07:10 <-     s: f8cecc9dccf6824cd9a0d1c20474233c
DEBUG 2019/02/07 11:07:12 Switch is off
DEBUG 2019/02/07 11:07:17 Switch is on
DEBUG 2019/02/07 11:07:18 192.168.10.111:50342 POST /pair-setup
DEBUG 2019/02/07 11:07:18 ->     A: f365c2b97350c76a6b35be880d2edfc6bf7b57e9f13430c4f319645ae292b6174b95e0c7171293382b60c7ada8b2af787e7a43a2623f05f4a3fbd61956810b802619dcc145b2fb2e73651aeba88efb1dbebee903d87b17ec6cce52ca2279fa81b776ba14d369a92242d9ec90596843bbdc0a6cef180c9607da5c1d3843eb6273f403813ca2222e1faf2ec8f87f43264c0069fa94d6129f9efa909e0248d6eb9c90a763054b044ddb785cbcbc492788837e1a4397bfe890de039bd719afbcc2389496bbc08d14742e69704b405c1da3d130f862dea5628f5beb6175c254d9bd62c9eeaee25d3a5ea16f836e0e0187dee58433b0a0e8a66fa04b159924c591c9830cdfaa1438934f21ee5f4219530b0c127fb84189b55cce9524d4377ce6af3aaa474ce03f1a86b3e73cf1eecfbf57ccdf212dc47742ac4c2c7aa4480d1293d9e9591a5a8bdf870469b9d725204ec32c8e68ce8fafc9499fcbfad01ef813f541063ca34901799b417cf28d6cc5d40abfc5fea17deef0208cc3f9bed1c6b4684e80
DEBUG 2019/02/07 11:07:18 ->     M1: 52eadb3392b9b5238f15b3234998d21a0fe9992398148143daff9b9d94c87bf2b76fce884c705d85bdad5c412b7f79876640995c6a2b1a008e32f2e5aa0c610f
DEBUG 2019/02/07 11:07:18 Proof M1 is valid
DEBUG 2019/02/07 11:07:18 <-     M2: a455d151436ea38f2058fae368498a9c007461e62641b7881948c3c2d289683faddaba2df326079fe98466c54a7efe29265ac33e04bac14c1657b8b546dccd38
DEBUG 2019/02/07 11:07:18         S: 3cfe590df1dc417f1b815a4e6def1701829c09b48e725813ca42cb318d769eb7fe8e9994b1f8d95033c9fce6adf92adeef901d43f76ed266a27af52d72ce20d1
DEBUG 2019/02/07 11:07:18         K: 19ebbed8a53dc9ffcaeee056a6e4b41e8b72c4a60c0e71dd3d761a14a31fd87a
DEBUG 2019/02/07 11:07:18 192.168.10.111:50342 POST /pair-setup
DEBUG 2019/02/07 11:07:18 ->     Message: 4f85932a53c2ec63f6ae5f38b8e20fe213543a3798192653dc6687daadcf31b7f279d1fba60079ce3a18c8c3cc040ac2c09733b371911255c6c6734fcc9b96d56148ea1175a2b81b316d43373bca1cb2c695ca628872360fb44709db94187beb3209bed79122e4bece0f5611498b85338dd8ed67459922738f46a453c235a54d63bd41003bdd2fb63e9b
DEBUG 2019/02/07 11:07:18 ->     MAC: 1cb102daa727d63756b01f642210a150
DEBUG 2019/02/07 11:07:18 ->     Username: B22DA38E-1640-4E1C-A7A1-54B1A6173A62
DEBUG 2019/02/07 11:07:18 ->     ltpk: 9c4d3a0000d56544a0b0c4ba3ff9bf5ce0294b215fb379a7e624e775fb44ea86
DEBUG 2019/02/07 11:07:18 ->     Signature: 9c949939719cf0fb78e11cf86e094a63ccee51d04a7cb91a0bde162dc01196825a7ef8059b8d8544a46179968dd3445d9bae4cb89415ee03d3b670449862fe0a
DEBUG 2019/02/07 11:07:18 ed25519 signature is valid
DEBUG 2019/02/07 11:07:18 Stored ltpk '9c4d3a0000d56544a0b0c4ba3ff9bf5ce0294b215fb379a7e624e775fb44ea86' for entity 'B22DA38E-1640-4E1C-A7A1-54B1A6173A62'
DEBUG 2019/02/07 11:07:18 <-     Username: 5a:19:a6:c0:70:e9
DEBUG 2019/02/07 11:07:18 <-     ltpk: 07fa91a03bce3007f8fdc6a1d4a33f0675e4b372d3e117cf6bd1d475d7eeb158
DEBUG 2019/02/07 11:07:18 <-     Signature: affd97da407b53cf83ec39d9f6f5eb2b79cacd8d944023d3ec86196119e193c89954ec11e988e2cc5038b9bd8ce9e4694cea276e163b85e07691ade0ab174509
DEBUG 2019/02/07 11:07:18 Event: paired with device
DEBUG 2019/02/07 11:07:20 Close connection and remove session
DEBUG 2019/02/07 11:07:20 192.168.10.111:50343 POST /pair-verify
DEBUG 2019/02/07 11:07:20 Create new pair verify controller
DEBUG 2019/02/07 11:07:20 ->     A: e38a2c25347ac897dbf24397d1981fbf7171dab237d81dce36dd978c5708b64c
DEBUG 2019/02/07 11:07:20        K: 3b6ae9543553cab8c4e045b63836a5bc94017cbcb9b288ae280f78837c05feb0
DEBUG 2019/02/07 11:07:20        B: a804388ab71b1115fa5e22344106893454efeeeacec40699ef460a5218032f42
DEBUG 2019/02/07 11:07:20        S: a90b8090640d7946110a1ae005d22923b83029adee02ce29f44540912fc03505
DEBUG 2019/02/07 11:07:20   Shared: e3b9251fb4028b1a2089517ab4567fc3b3b3599f0b23d4e2d3181160539d4921
DEBUG 2019/02/07 11:07:20 <-     B: a804388ab71b1115fa5e22344106893454efeeeacec40699ef460a5218032f42
DEBUG 2019/02/07 11:07:20 192.168.10.111:50343 POST /pair-verify
DEBUG 2019/02/07 11:07:20 ->     Message: 4bb52fcd154fefbcc2bda0711e452540e92556f873d67438d3d011a3a77e0c73f495c29b8843420857cc6a31db6509bf04fa2fbc4e71eff2a0d29bf281c8b381af877eba3d44879ca5e32fa889a34830ea5e1e338ffe5d1fd096a05012a3c2d9ef070e39a571cfe9
DEBUG 2019/02/07 11:07:20 ->     MAC: 199cf4b4a6517d68df7e9d8893c4bc91
DEBUG 2019/02/07 11:07:20     client: B22DA38E-1640-4E1C-A7A1-54B1A6173A62
DEBUG 2019/02/07 11:07:20  signature: 15f189f7667523f7d5fd428255d22b3b5b87b7648713ce7222b5b7ac8b5948f4a8a1fb03c51f5f171940e4625cd1a43f96abd023eb835bc0617de41a7c34370c
DEBUG 2019/02/07 11:07:20 signature is valid
DEBUG 2019/02/07 11:07:20 Setup secure session
DEBUG 2019/02/07 11:07:20 192.168.10.111:50343 GET /accessories
DEBUG 2019/02/07 11:07:20 {"accessories":[{"aid":1,"services":[{"iid":1,"type":"3E","characteristics":[{"iid":2,"type":"14","perms":["pw"],"format":"bool"},{"iid":3,"type":"20","perms":["pr"],"value":"undefined","format":"string"},{"iid":4,"type":"21","perms":["pr"],"value":"undefined","format":"string"},{"iid":5,"type":"23","perms":["pr"],"value":"Lamp1","format":"string"},{"iid":6,"type":"30","perms":["pr"],"value":"undefined","format":"string"},{"iid":7,"type":"52","perms":["pr"],"value":"","format":"string"}]},{"iid":8,"type":"49","characteristics":[{"iid":9,"type":"25","perms":["pr","pw","ev"],"value":true,"format":"bool"}]}]}]}
DEBUG 2019/02/07 11:07:20 192.168.10.111:50343 PUT /characteristics
DEBUG 2019/02/07 11:07:20 {"characteristics":[{"aid":1,"iid":9,"ev":true}]}
DEBUG 2019/02/07 11:07:20 192.168.10.111:50343 PUT /characteristics
DEBUG 2019/02/07 11:07:20 {"characteristics":[{"aid":1,"iid":9,"ev":true}]}
DEBUG 2019/02/07 11:07:22 Switch is off
DEBUG 2019/02/07 11:07:22 192.168.10.111:50343 <- EVENT/1.0 200 OK
Content-Length: 53
Content-Type: application/hap+json

{"characteristics":[{"aid":1,"iid":9,"value":false}]}
DEBUG 2019/02/07 11:07:22 192.168.10.111:50343 GET /characteristics
DEBUG 2019/02/07 11:07:23 192.168.10.111:50343 PUT /characteristics
DEBUG 2019/02/07 11:07:23 {"characteristics":[{"aid":1,"iid":2,"value":true}]}
DEBUG 2019/02/07 11:07:27 Switch is on
DEBUG 2019/02/07 11:07:27 192.168.10.111:50343 <- EVENT/1.0 200 OK
Content-Length: 52
Content-Type: application/hap+json

{"characteristics":[{"aid":1,"iid":9,"value":true}]}
DEBUG 2019/02/07 11:07:32 Switch is off
DEBUG 2019/02/07 11:07:32 192.168.10.111:50343 <- EVENT/1.0 200 OK
Content-Length: 53
Content-Type: application/hap+json

{"characteristics":[{"aid":1,"iid":9,"value":false}]}
DEBUG 2019/02/07 11:07:35 192.168.10.111:50343 GET /characteristics
DEBUG 2019/02/07 11:07:37 Switch is on
DEBUG 2019/02/07 11:07:37 192.168.10.111:50343 <- EVENT/1.0 200 OK
Content-Length: 52
Content-Type: application/hap+json

{"characteristics":[{"aid":1,"iid":9,"value":true}]}
DEBUG 2019/02/07 11:07:42 Switch is off
DEBUG 2019/02/07 11:07:42 192.168.10.111:50343 <- EVENT/1.0 200 OK
Content-Length: 53
Content-Type: application/hap+json

{"characteristics":[{"aid":1,"iid":9,"value":false}]}
DEBUG 2019/02/07 11:07:45 Close connection and remove session
DEBUG 2019/02/07 11:07:45 Decryption failed: read tcp 192.168.10.145:12345->192.168.10.111:50343: use of closed network connection
DEBUG 2019/02/07 11:07:45 Close connection and remove session
DEBUG 2019/02/07 11:07:45 server stopped
DEBUG 2019/02/07 11:07:46 mdns responder stopped
`

Restart:
`DEBUG 2019/02/07 11:08:24 Switch is on
INFO 2019/02/07 11:08:24 Accessory address is 192.168.10.145:12345
DEBUG 2019/02/07 11:08:29 Switch is off
DEBUG 2019/02/07 11:08:34 Switch is on
DEBUG 2019/02/07 11:08:39 Switch is off
DEBUG 2019/02/07 11:08:44 Switch is on
DEBUG 2019/02/07 11:08:49 Switch is off
DEBUG 2019/02/07 11:08:54 Switch is on
DEBUG 2019/02/07 11:08:59 Switch is off
DEBUG 2019/02/07 11:09:04 Switch is on
DEBUG 2019/02/07 11:09:09 Switch is off
DEBUG 2019/02/07 11:09:14 Switch is on
DEBUG 2019/02/07 11:09:19 Switch is off
DEBUG 2019/02/07 11:09:24 Switch is on
DEBUG 2019/02/07 11:09:29 Switch is off
DEBUG 2019/02/07 11:09:34 Switch is on
DEBUG 2019/02/07 11:09:39 Switch is off
DEBUG 2019/02/07 11:09:44 Switch is on
DEBUG 2019/02/07 11:09:49 Switch is off
DEBUG 2019/02/07 11:09:54 Switch is on
DEBUG 2019/02/07 11:09:59 Switch is off
DEBUG 2019/02/07 11:10:04 Switch is on
DEBUG 2019/02/07 11:10:09 Switch is off
DEBUG 2019/02/07 11:10:14 Switch is on
DEBUG 2019/02/07 11:10:19 Switch is off
DEBUG 2019/02/07 11:10:24 Switch is on`

**Comment by brutella** [comment]
In your program do you explicitly specify a storage path using `Config.StoragePath`?

If you're not, then changing the name of the accessory also changes the path where are persistent data is stored. This means that your new accessory is not paired yet.

Side note: I will integrate  [dnssd v1.1](https://github.com/brutella/dnssd/tree/v1.1.0) into hc soon, which might fix your dns issue.

**Comment by radionoise** [comment]
I was using the source code from `_example/example.go`, so yes, storage path was explicitly declared. I was removing the .db directory after trying to pair the second time. Also when I try to run program twice, the accessory is not getting updates for 5-10 minutes. Will try when dnssd 1.1 will be integrated.
