### ISSUE TITLE
Add optional characteristics to generated services 

### ISSUE THREAD

**Issue by rbg** [brutella/hc#137]
Noted that optional characteristics are not auto generated from "cmd/import.go" 

-- PR on it's way

**Comment by jmhodges** [comment]
Hey, I see a commit was made, but I don't see a PR. Any news on that?

**Comment by brutella** [comment]
This is intended because optional characteristics depend on the use case. For example, it wouldn't make any sense to include all optional characteristics for heater cooler service.
