### ISSUE TITLE
Can't associate accessory when name contains accents or punctuation

### ISSUE THREAD

**Issue by ferllings** [brutella/hc#144]
Hello,

I'm playing with your lib and I noticed I can't associate any accessory when the label contains an accent or a punctuation char.

I can see the accessory in the list, but after typing the PIN, the accessory is not responding.
Eg. : "Salle à manger, Plafond" (doesn't work)
"Salle a manger Plafond" (works)

**Comment by brutella** [comment]
This should be fixed in v1.2.1.
