### ISSUE TITLE
Question: Best way to handle multiple accessories

### ISSUE THREAD

**Issue by ferllings** [brutella/hc#145]
Hello,

Is it possible to have an example with multiple accessories? In particular if it possible to use the same IP transport server to expose all accessories.

I'm trying to build a KNX/Homekit gateway, and I have 50-60 devices in total.

Thanks in advance,

**Comment by timoschilling** [comment]
maybe this will help you:
https://github.com/timoschilling/fritzbridge

**Comment by ferllings** [comment]
Thanks that's very helpful !!
