### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by maaraneasi** [brutella/hc#146]
Hey all!
I am so happy I found this project!!! :-)
I don't have exactly "an issue" but rather a very noob question, need small help and don't know where else to ask...
I am trying to create multiple accessories at the same time as it seems to be supported by the ip transport:
"The transports can contain more than one accessory. If this is the case, the first accessory acts as the HomeKit bridge."
...yet I got stuck here... 
I have a map of the accessories (my code needs to store the device name and its unique address I am passing to the ON/OFF commands which communicate further via telnet), but I am not sure how to properly construct multiple accessories from this map and pass all the accessories to the transport...
My idea is to build a slice and pass it to the transport, yet the is the place where I got unsure:
1) The example creates `acc := accessory.NewLightbulb(info)`, but what if I have more light bulbs? Should I create a slice and append all these `acc's` (if so then of what type this slice should be?)?
I tried to create a slice `var lampSlice []*accessory.Lightbulb` and fed my custom lightbulbs into this slice, yet I can't use this slice in NewIPTransport() and this function expects `*accessory.Accessory`.......
2) how to handle functions like `acc.Lightbulb.On.OnValueRemoteUpdate(func(on bool) {}` which are created for the accessory which are created for the specific accessory? 

Is there an example of creating multiple accessories I could check and consult with?
Thanks a lot!

**Comment by brutella** [comment]
> 1. The example creates acc := accessory.NewLightbulb(info), but what if I have more light bulbs? Should I create a slice and append all these acc's (if so then of what type this slice should be?)?
I tried to create a slice var lampSlice []*accessory.Lightbulb and fed my custom lightbulbs into this slice, yet I can't use this slice in NewIPTransport() and this function expects *accessory.Accessory.......

If you have a map of light bulb accessories, you have to convert it to a slice of generic accessories like this.

```go
var lights map[string]*accessory.Lightbulb
var accessories []*accessory.Accessory
for (string, light) := range lights {
    accessories = append(accessories, light.Accessory)
}
```

Then you can create an ip transport with the `accessories` slice.

> 2. how to handle functions like acc.Lightbulb.On.OnValueRemoteUpdate(func(on bool) {} which are created for the accessory which are created for the specific accessory?

I would create a function which takes the telnet address and returns a light bulb accessory.
Inside this method you create an accessory and implement the `acc.Lightbulb.On.OnValueRemoteUpdate(func(on bool) {})` callback. 

There you have all the information you need to implement the two-way communication between telnet and HomeKit.

**Comment by maaraneasi** [comment]
Will give it a try! Thanks for help and thanks for such a great implementation (and sorry for my questions - this is one of my early attempts writing in golang...)

**Comment by maaraneasi** [comment]
I got is partially working but seems I am doing something terribly wrong (still fighting with the types in golang tbh)........
I am able to communicate with the device via telnet and it works just fine but it works with only one device - if I add the slice to the function parameter (`t, err := hc.NewIPTransport(hc.Config{Pin: "11223344"}, acc.Accessory, accessories...)`, I see the bridge device (which is basically yet another lightbulb I define separately but which uses the same code for turning on and off..), but I can't connect to it (can't add it to the household).

The way I am building the lights map is:

```
func deviceBuilder(objectmap map[string]*cuobject, acctype int) { //Thie object map is a map of strings and struct
for _, object := range objectmap {
log.Printf("Building object: &s", object)
                                 accInfo := accessoryInfoFiller(object.address, object.alias)
				log.Printf("Info Struct2: %+v\n", *accInfo)
				acc := accessory.NewLightbulb(*accInfo)
				log.Printf("Accessory object : &s", &acc)
				log.Printf("Accessory object2: %+v\n", *acc)
				acc.Lightbulb.On.OnValueRemoteUpdate(func(on bool) {
					if on == true {
						turnLightOn(object.address)
					} else {
						turnLightOff(object.address)
					}
				})

				lights[object.address] = acc
```

To build the device info, I am using this `accessoryInfoFiller()` function which takes the object address (the device ID I use in the telnet call) and object alias (name of the device):

```
func accessoryInfoFiller(serialNr string, accName string) *accessory.Info {
	i := accessory.Info{Name: accName}
	i.SerialNumber = serialNr
	i.Manufacturer = "Test device"
	log.Printf("Info Struct: %+v\n", i)
	return &i
}
```

I take the data returned by this function and create a lightbulb object: `acc := accessory.NewLightbulb(*accInfo)`. For this acc object, I create the ON/OFF function and append it to the lights map: `lights[object.address] = acc` where the address is the key.

The dirty and unformatted debug logging for one of the objects looks like this:

```
2019/09/10 08:45:14 Building object: &s%!(EXTRA *main.cuobject=&{RE1PRACOVNADOWN 0x0102000D 0x00000000  1 2})
2019/09/10 08:45:14 Info Struct: {Name:RE1PRACOVNADOWN SerialNumber:0x0102000D Manufacturer:Test Model: FirmwareRevision:}
2019/09/10 08:45:14 Info Struct2: {Name:RE1PRACOVNADOWN SerialNumber:0x0102000D Manufacturer:Test Model: FirmwareRevision:}
2019/09/10 08:45:14 Accessory object : &s%!(EXTRA **accessory.Lightbulb=0xc0002776a0)
2019/09/10 08:45:14 Accessory object2: {Accessory:0xc000292d00 Lightbulb:0xc0002b0120}
```

I end up with the light map as below:
```
2019/09/10 09:12:01 Built: &s objects%!(EXTRA map[string]*accessory.Lightbulb=map[0x01020001:0xc00027d360 0x01020003:0xc00023d210 0x01020004:0xc000258a70 0x01020005:0xc00023c570 . . . . . 
```
which I use for building the accessory slice using:

```
var accessories []*accessory.Accessory
	for _, light := range lights {
		accessories = append(accessories, light.Accessory)
	}
```

this makes the slice I am using for passing to the transport (about 150 entries):

```
2019/09/10 09:12:01 All accessories slice: [%!s(*accessory.Accessory=&{0 [0xc0001956e0 0xc000195740] 5 0xc0001f3b80 1 <nil>}) %!s(*accessory.Accessory=&{0 [0xc000242480 0xc0002424e0] 5 0xc000221800 1 <nil>}) . . .
```

When I run the code, I can see a directory with the bridge name created, but not for any of the other accessories, I can see the bridge in the phone app but it's saying it couldn't connect to it.
Did I screw it? Is there some debug logging I can turn on so I can see what is wrong with all this "additional" accessory I am passing to the transport? 
Is there a limitation on how many devices I can create?

If anyone could point me to the place where I did it wrong, I'd be grateful... :(

**Comment by maaraneasi** [comment]
Seems I panicked prematurely (and deleted my previous comment) :-)  My issue is that I am passing too many devices to the transport - is there any limitation? - I was trying to send about 150 devices to the transport (all the relays on the control unit) what seems too many. I went down to 4 and it works fine (almost). The only issue I have is that I am able to control only one of the created lightbulbs  (which is the very first one I turn on after starting the program)... If I check the phone app, I see the devices having the correct SN (which is the telnet address) but any ON / OFF call is reusing the address of the first device I turned on....

I am setting the on / off action in the same loop where I am creating the accessory object:
```
for _, object := range objectmap {
		if object != nil {
				log.Printf("Building object: &s", object)
				accInfo := accessoryInfoFiller(object.address, object.alias)
				log.Printf("Info Struct2: %+v\n", *accInfo)
				acc := accessory.NewLightbulb(*accInfo)
				log.Printf("Accessory object : &s", &acc)
				log.Printf("Accessory object2: %+v\n", *acc)
				log.Printf("Accessory object3: %+v\n", acc)
				acc.Lightbulb.On.OnValueRemoteUpdate(func(on bool) {
					if on == true {
						turnLightOn(object.address)
						log.Println("Action ON: %v", object.address )
					} else {
						turnLightOff(object.address)
						log.Println("Action OFF: %v",  object.address)
					}
				})
				lights[object.address] = acc
```
...and where I am filling in the accessory info (which is correct for each object)
```
func accessoryInfoFiller(serialNr string, accName string) *accessory.Info {
	i := accessory.Info{Name: accName}
	i.SerialNumber = serialNr
	i.Manufacturer = "Test device"
	log.Printf("Info Struct: %+v\n", i)
	return &i
}
```

The ON/ OFF action is the one from the example and it expects 
ie.
```
func turnLightOn(deviceAddress string) {
	log.Println("Turn Light On:")
	log.Println("ON command: %s", "SET,"+deviceAddress+",1")
	Telnet_connect("SET," + deviceAddress + ",1")
}
```

The problem is that if I toggle the device (for example) 0x01020027, all the other ON / OFF actions will be using the same device SN instead of SN of the accessory I am trying to control:
```
2019/09/10 11:48:00 Turn Light On:
2019/09/10 11:48:00 ON command: %s SET,0x01020027,1
2019/09/10 11:48:00 Calling telnet with %s SET,0x01020027,1
2019/09/10 11:48:00 Action ON: %v &{0xc0001100d8}
2019/09/10 11:48:05 Turn Light On:
2019/09/10 11:48:05 ON command: %s SET,0x01020027,1
2019/09/10 11:48:05 Calling telnet with %s SET,0x01020027,1
2019/09/10 11:48:05 Action ON: %v &{0xc0000c2060}
2019/09/10 11:48:13 Calling telnet with %s SET,0x01020027,0
2019/09/10 11:48:13 Turn Light Off:
2019/09/10 11:48:13 OFF command: %s SET,0x01020027,0
2019/09/10 11:48:13 Action OFF: %v &{0xc0000c2060}
2019/09/10 11:48:17 Calling telnet with %s SET,0x01020027,0
2019/09/10 11:48:17 Turn Light Off:
2019/09/10 11:48:17 OFF command: %s SET,0x01020027,0
2019/09/10 11:48:17 Action OFF: %v &{0xc0001100d8}
```

creating the accessory:

```
2019/09/10 11:47:49 Building object: &s%!(EXTRA *main.cuobject=&{RE2OBYVAKPODHLED 0x01020026 0x00000000  1 2})
2019/09/10 11:47:49 Info Struct: {Name:RE2OBYVAKPODHLED SerialNumber:0x01020026 Manufacturer:Test device Model: FirmwareRevision:}
2019/09/10 11:47:49 Info Struct2: {Name:RE2OBYVAKPODHLED SerialNumber:0x01020026 Manufacturer:Test device Model: FirmwareRevision:}
2019/09/10 11:47:49 Accessory object : &s%!(EXTRA **accessory.Lightbulb=0xc0000c20d8)
2019/09/10 11:47:49 Accessory object2: {Accessory:0xc0000c6180 Lightbulb:0xc0000a4270}
2019/09/10 11:47:49 Accessory object3: &{Accessory:0xc0000c6180 Lightbulb:0xc0000a4270}
2019/09/10 11:47:49 Building object: &s%!(EXTRA *main.cuobject=&{RE3OBYVAKKRB 0x01020027 0x00000000  1 2})
2019/09/10 11:47:49 Info Struct: {Name:RE3OBYVAKKRB SerialNumber:0x01020027 Manufacturer:Test device Model: FirmwareRevision:}
2019/09/10 11:47:49 Info Struct2: {Name:RE3OBYVAKKRB SerialNumber:0x01020027 Manufacturer:Test device Model: FirmwareRevision:}
2019/09/10 11:47:49 Accessory object : &s%!(EXTRA **accessory.Lightbulb=0xc000110088)
2019/09/10 11:47:49 Accessory object2: {Accessory:0xc0000b6540 Lightbulb:0xc0000b8e40}
2019/09/10 11:47:49 Accessory object3: &{Accessory:0xc0000b6540 Lightbulb:0xc0000b8e40}
2019/09/10 11:47:49 Built: &s objects%!(EXTRA map[string]*accessory.Lightbulb=map[0x01020025:0xc0000a2250 0x01020026:0xc0000a2370 0x01020027:0xc0001168d0])
```

(sorry for the formatting of the debug prints and my terrible way of coding - I didn't care about the logs so far and all the pointers and types are still very confusing for me).
Any idea where did I screw it?

**Comment by bjanders** [comment]
> My issue is that I am passing too many devices to the transport - is there any limitation? - I was trying to send about 150 devices to the transport (all the relays on the control unit) what seems too many. 

The HomeKit Accessory Protocol (HAP) specification sets a limit of 150 accessories per bridge.

**Comment by maaraneasi** [comment]
Thanks for confirming - I thought that I might be too demanding by not filtering out what I really need and passing all the relays to the protocol :-)
I am currently testing with 4 devices and it works fine (mostly). What is weird is that sometimes, when I run the program, it mixes the device addresses so the homekit app switches turn on random devices (although reliably and consistently). Checking the device address in the app (I can see the device SN in the device details), it's all correct yet the on/off actions are using a different SN they took "somewhere", so I had to stop the app, restart and it eventually restarts with the correct device name and sn binding. When checking by debug output, it builds the devices with the correct addresses so not sure how it gets so mixed up

**Comment by bjanders** [comment]
Devices (accessories) in HomeKit are identified by an ID. hc assigns the ID incrementally in the order you add them in the `NewIPTransport()` call. So if the order of your devices changes when you start up your application, then they will get mixed up in the Home app. This is a problem if you later add new devices to hc. For example, I initially started with a bridge (ID 1) and two thermostats (IDs 2, 3). I then added five window shades (IDs 4-8). Then I added a third thermostat. In my app I first add all thermostats and then all shades. Now, when I added the third thermostat it got ID 4, and all all shades got an ID that was incremented by one compared to the initial setup (IDs 5-9), and things were mixed up in the Home app. It showed a sixth shade (ID 9) and the third thermostat was not visible, because the Home app thought that ID  4 was a shade. think it would be better if one could assign the IDs yourself in hc, so that you could keep a consistent numbering, for example as part of the  `accessory.Info` struct.

**Comment by brutella** [comment]
@bjanders That's a good point. Pull requests are always welcome. 😉

**Comment by bjanders** [comment]
I did a quick hack for my own purposes, but if there is chance for a proper change to get merged then I'll try to get it done. I'd make it so that it is backward compatible so that if you don't provide a custom ID then one would be assigned incrementally as it is done now. If you assign a custom ID I'd a check that that ID is not already assigned to some other accessory.

**Comment by maaraneasi** [comment]
> hc assigns the ID incrementally in the order you add them in the NewIPTransport() call. 

This sounds like the tricky part. I am loading my devices from a text file (which is being produced by my smart home control unit). I am currently having about 25 lights I am feeding into the transport and loading them from a slice changes their ID if I restart the app so its impossible to restart the app without deleting everything and adding all the devices in the ios app again.

**Comment by brutella** [comment]
We could add an ID property to accessory.Info and use that if specified.
Any thoughts on this?

**Comment by mologie** [comment]
I second adding an ID property to accessory.Info. Implementing dynamic bridges, where accessories are added after the fact or may disappear when decomissioned, is not possible otherwise.

This is also a good place to change the ID type to an int64: Currently, a 32-bit int is used, but the HAP spec (section 2.6.1) allows 64-bit instance IDs for IP accessories. Switching to a 64-bit ID would enable trivial mapping to IDs for bridges, e.g. by hashing an object-unique identifier and using that as ID.

**Comment by brutella** [comment]
Thanks, those changes are now available in the master branch.
