### ISSUE TITLE
Can't find the camera in HomeKit after reinstalling the HKCam-Image.

### ISSUE THREAD

**Issue by HKFanBoy** [brutella/hc#152]
Hi,

I installed the HKCam-Image (0.0.9) to my RPI Zero and it worked. But after removing the camera from Homekit and changing the SD-Card in the RPI (with the same image burnt on) HomeKit won't find the camera anymore. 
Does anybody have any suggestions what I can do?
Unfortunately I have no programming experiences at all, so I can't find the problem by myself.

Thank for your help in advance!

**Comment by brutella** [comment]
Remove all persistent data related to hkcam.

```shell
rm -rf /var/lib/hkcam/data
```

Then restart the RPi Zero.
