### ISSUE TITLE
 pairing verify step error

### ISSUE THREAD

**Issue by onderweg** [brutella/hc#154]
After (successfully) running an IP transport accessory for some time (couple of minutes to couple of hours), I get the following error:

```
pair-verify.go:59: Invalid internal pairing verify step Waiting
```
After that, Homekit won't show notifications for the device anymore on my iOS devices.
After removing/re-adding device in homekit, and restarting hc accessory, things are working again.

Any ideas how to resolve this?

**Comment by brutella** [comment]
This should be fixed in v1.2.1
Let me know if it still doesn't work.

**Comment by onderweg** [comment]
Thanks! I'll let you know

**Comment by onderweg** [comment]
Work perfectly now 👍 . Thanks a lot for this project.
