### ISSUE TITLE
discovery example doc

### ISSUE THREAD

**Issue by jmhodges** [brutella/hc#159]
It would be cool to have some explicit documentation on how to list all of the available HomeKit accessories currently on the network. I don't currently see how to make that work.

(This functionality would be similar to homebridge's `/accessories` path you can `GET`)

**Comment by jmhodges** [comment]
I found the `endpoint.Accessories` HTTP handler,

**Comment by jmhodges** [comment]
Hrm, I've misread what homebridge's `/accessories` did, it seems.

**Comment by jmhodges** [comment]
Actually, I'm going to re-open this, because it would be nice to have `hc` provide a way to list homekit accessories on the network.

**Comment by brutella** [comment]
Please describe in more detail what this feature should actually do.

**Comment by jmhodges** [comment]
A function similar to the guts of https://github.com/brutella/dnssd/tree/master/cmd/browse that would return the Accessories on the network. This would let me pick out the Accessory I needed from only a subset of the information required (say, just the Accessory name, or its available Services).

**Comment by brutella** [comment]
Seeing a list of HomeKit accessories can be done by browsing the `_hap._tcp` dnssd service types. 
Of course you can use [dns-sd](https://github.com/brutella/dnssd) to do that.
There is no need to implement that in `hc`.
