### ISSUE TITLE
github.com/agl/ed25519 repo is dead

### ISSUE THREAD

**Issue by e1z0** [brutella/hc#167]
4 days ago the repository was moved...

../go/src/github.com/brutella/hc/crypto/ed25519.go:5:2: no Go files in /root/go/src/github.com/agl/ed25519

It moved to https://godoc.org/golang.org/x/crypto/ed25519

But it does not compile either, maybe some functions or calls are incompatible :)

**Comment by worepix** [comment]
There will be little code change, it is just repository move. When I tried to change repository how documentation says. Some type errors just appeared.

```
# github.com/brutella/hc/crypto
../../../go/src/github.com/brutella/hc/crypto/ed25519.go:21:24: cannot use &k (type *[32]byte) as type "crypto/ed25519".PublicKey in argument to "golang.org/x/crypto/ed25519".Verify
../../../go/src/github.com/brutella/hc/crypto/ed25519.go:21:34: cannot use &s (type *[64]byte) as type []byte in argument to "golang.org/x/crypto/ed25519".Verify
../../../go/src/github.com/brutella/hc/crypto/ed25519.go:32:28: cannot use &k (type *[64]byte) as type "crypto/ed25519".PrivateKey in argument to "golang.org/x/crypto/ed25519".Sign
```

**Comment by marek-memsql** [comment]
The same issue here - I can no longer build... :(

**Comment by brutella** [comment]
Sorry for this to take so long.

FYI: Go 1.13 is now required with this change.
