### ISSUE TITLE
doorbell implementation

### ISSUE THREAD

**Issue by ra1nb0w** [brutella/hc#176]
Hi,
first of all, thank you to share your hard work!
I am trying to implement a basic version of doorbell on my mac: camera + audio from camera + audio from ios. I am using as template your hkcam project and camera with audio from camera works fine. Now I would to move from `accessory.NewCamera()` to create a new accessory, something like `accessory.NewDoorbell()` where `acc.Control = service.NewDoorbell()` and then I will add IPCamera as service? Or just create two accessory and then link doorbell and IPCamera? (I am not sure about the last since I see `TypeVideoDoorbell` as AccessoryType ). What should be the workflow?
Ps. do you know something on how to manage the audio flow from ios to camera?

thank you very much and have a nice weekend.

**Comment by brutella** [comment]
Please try to create a video doorbell accessory using the HomeKit Accessory Simulator (which is included in **Additional Tools for Xcode 11** from https://developer.apple.com/downloads) and check which services are required for a video doorbell.

**Comment by ra1nb0w** [comment]
thank you very much for the answer. In the meantime, I built a working doorbell and the only things that I don't understand is how to enable the speaker audio session (ios mic). I check the simulator.
