### ISSUE TITLE
Health check?

### ISSUE THREAD

**Issue by travishaagen** [brutella/hc#179]
I periodically have to restart `hc` and have had trouble determining why from the logs. 

Do you have any ideas of a "heath check" request that could be sent over the network?

**Comment by brutella** [comment]
If an accessory is not reachable, I always use [Discovery app](https://apps.apple.com/us/app/discovery-dns-sd-browser/id305441017) to find the related dns-sd entry of type `_hap._tcp` for the accessory. This tells me if anything is wrong with `hc` or the network.

PS: I'm currently working [dnssd](https://github.com/brutella/dnssd) to fix some small issue. Maybe those are related to your problem.

**Comment by travishaagen** [comment]
Should I test the unreleased changes on dnssd `master` or are you still working on them? going to release?

**Comment by brutella** [comment]
If you want to test the unreleased changes of `dnssd` you should checkout the branch `refactoring` of `dnssd`.

```shell
go get github.com/brutella/dnssd
cd $GOPATH/src/github.com/brutella/dnssd
git checkout refactoring
```

Then in your `go.mod` use

```
replace github.com/brutella/dnssd => ./<path-to-dnssd-folder>
```
