### ISSUE TITLE
Manage characteristic events per socket

### ISSUE THREAD

**Issue by brutella** [brutella/hc#180]
An event message is sent to all connected clients if events are enabled and a characteristic value changes.
If one client disables events, all other clients miss the events as well.

I think it would be better to manage events per connected socket, so that other clients can't disable events for all others.

**Comment by JayFiDev** [comment]
Could you add a litte pointer where this functionality is located? This would make it easier for others to help you when they are not too deep into your code yet.

**Comment by brutella** [comment]
I will publish a fix for this issue very soon.

**Comment by JayFiDev** [comment]
Any other issues/features you want help for? Maybe you could add some more issues with the „enhancement“ or „help needed“ tag.

**Comment by brutella** [comment]
Fixed in [v1.2.3](https://github.com/brutella/hc/releases/tag/v1.2.3)
