### ISSUE TITLE
ventilation unit

### ISSUE THREAD

**Issue by hazcod** [brutella/hc#185]
Hi, i'm strongly thinking about writing a serial controller for a Dubox Energy Premium ventilation system. (type D)
I don't seem to see any relatable accessory types for a ventilation unit? 
Many thanks for your work.

**Comment by hazcod** [comment]
@brutella ?

**Comment by brutella** [comment]
Maybe you could use a [Heater Cooler](https://github.com/brutella/hc/tree/master/service) service for this?

**Comment by hazcod** [comment]
I guess so, thanks!
