### ISSUE TITLE
Scenes

### ISSUE THREAD

**Issue by khwerhahn** [brutella/hc#188]
Hi, 

this is a more general question on understand HomeKit and hc. I haven't found anything about "scenes". I can create scenes via the Eve app or Hue and they can be seen in Homekit (Home App). Can i interact with them via hc?

Use case: My automations have gotten out of hand and I want to build myself an app where I can see in realtime which automations (scenes) triggered a device to do something (e.g. wh did this lamp just turn off).

**Comment by brutella** [comment]
No, scenes are a concept in HomeKit and not the underlying protocol. You only have access to scenes with an iOS (or macOS Catalyst) app by using the HomeKit framework.
