### ISSUE TITLE
accessory tv

### ISSUE THREAD

**Issue by xxandev** [brutella/hc#194]
Hi
I have a question on TV
all characteristics of the device are not displayed
only Active and Input Sources
LIB hc 1.2.3 (aac10474c5d81a74dc91be5db4cca38301d1ec8a)
GO 1.15.8
OS linux ubuntu 20.04 lts
Apple device ipad, OS 14.4

>>> this example doesn't work https://github.com/brutella/hc/blob/master/_example/tv/main.go
>>> Unable to Add Accessory (Accessory is out of compliance)
---
https://github.com/alpr777/homekit
https://github.com/alpr777/homekit/blob/main/accessory_television.go
https://github.com/alpr777/homekit/blob/main/example/television/main.go

**Comment by cloudkucooland** [comment]
https://github.com/cloudkucooland/TooFar/blob/main/devices/txnr686.go

That's a configuration that works for me. The AddInputs is pretty specific to this device, but I've got comments in there for what does and doesn't work as far as characteristics and services.

**Comment by alpr777** [comment]
no matter what I do, only 2 characteristics are still displayed (Active and Input Sources)

https://github.com/alpr777/homekit/blob/main/example/television/README.md

**Comment by cloudkucooland** [comment]
> no matter what I do, only 2 characteristics are still displayed (Active and Input Sources)
> 
> https://github.com/alpr777/homekit/blob/main/example/television/README.md

Those are the only two I've gotten to display as well. Volume is controlled, but not displayed (I use iPhone's volume buttons when in "remote" mode). The remote works as well, not quite as many features as with AppleTV, but it still works.

What else are you trying to get to show? Perhaps the home app doesn't actually display it for anything.

**Comment by alpr777** [comment]
I wanted a simple TV remote with a homekit) switching channels would be nice, more precisely, to be displayed Television.RemoteKey (Rewind, Exit, Play/Pause, Info, Next, Prev ...). Because many TVs are IP controlled, they have their own control applications. And if the Television.RemoteKey was displayed in the homekit, it would make it possible not to use the standard application.
Thank you for the answer)

**Comment by alpr777** [comment]
Sorry)
After you wrote that perhaps control should not come from the Homekit app
Everything became obvious)
It really is, you are right)
There is a service remote control

You helped me, thanks)

UPDATED:
https://github.com/alpr777/homekit/blob/main/example/television/README.md

**Comment by cloudkucooland** [comment]
Happy to help. Perhaps someone could write a macOS app to act as the remote too?

**Comment by Claywd** [comment]
Working on it the logic for an app. I may try and throw a GUI if I get some time after current project.
