### ISSUE TITLE
multiple accessories events

### ISSUE THREAD

**Issue by zuozhehao** [brutella/hc#202]
```
for k, v := arr {

  as := accessory.New(v.Conf, v.Type)
    _ = s.Container.AddAccessory(as)

}
```
I add accessories in a loop, but I find that I don't know how to set a callback for each accessory.

Can someone help.

**Comment by brutella** [comment]
Please explain your issue in more detail. What kind of accessories are you creating?

**Comment by brutella** [comment]
Closed because of inactivity.
