### ISSUE TITLE
bridge must not expose more than 150 objects

### ISSUE THREAD

**Issue by alpr777** [brutella/hc#206]
A bridge must not expose more than 150 HAP accessory objects. (HomeKit Accessory Protocol Specification R2)

func NewIPTransport
...
	t.addAccessory(a)
	for n, a := range as {
		if n > 150 {
			log.Info.Printf("a bridge must not expose more than 150 hap accessory objects.\n")
			break
		}
		t.addAccessory(a)
	}
...

**Comment by brutella** [comment]
That's true. I didn't include a hard limit because I don't want to get into the hassle of keeping that limit up to date when Apple changes the limit in a future iOS release.

It's up to the developer to handle that case.
