### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by oliverpool** [brutella/hc#209]
First of all, thank you   so much @brutella for this great project!

I'm starting to use this repo to make a bridge on my local network and I would like to ask you, what is the maintenance status of this repo. Apparently there wasn't much activity from your side since August last year.

- is it just a temporary phase and you plan to pursue the maintenance/management of this project soon?
- would you be willing to help some contributors become maintainers of this project, so that you can step down?
- or maybe you consider this project complete enough for you and would recommend the community to work together on a fork (not under the repo `brutella/hc`)?
- or some other solution?

Thank you

**Comment by brutella** [comment]
I'm using this library myself in a project and I will definitely keep working on it. This library is pretty stable and there is not much missing imho.

**Comment by oliverpool** [comment]
Alright, thank you for your reply!

What do you think about external contributions? (I see that there are a couple of opened MR without much activity lately)


(to be clear, I find it totally acceptable, for you not to take the time to look at them - but I think it would be fair to let the contributors know that their PR would probably not be merged)

**Comment by brutella** [comment]
FYI I've refactored hc and made a new library out of it called. The new implementation is much more simpler. The new library is available as [hap](https://github.com/brutella/hap).

**Comment by oliverpool** [comment]
Very nice !

If you are interested, I had some fun trying to refactor the code from `hc`. I managed to split the pairing/encryption stuff from the hap communication.

Feel free to take a look at it https://pkg.go.dev/git.sr.ht/~oliverpool/gohmbridge
Packages:
- `tlv8` tlv8 encoding & decoding
- `pairing`: pairing management. A HTTP server, which handles only `/pair-setup`, `/pair-verify`, `/pairings`, `/identify` and delegates all other URIs to the provided handler (subpackage `crypto` manages the crypto primitives).
- `hap`: wip to provide handlers for the accessory and co (staled, since I stopped working on it)
- `hcompat`: compatibility layer between my interfaces and the interfaces used by `hc`
- `kltv`: various constants

I had fun reimplementing all the pairing stuff and was able to have great test coverage thanks to your library!

I would be honored if you could took a look (feel free to copy some code, I published it under the same License as hc).
