### ISSUE TITLE
addition & examples 

### ISSUE THREAD

**Issue by xxandev** [brutella/hc#210]
i created a small addition for your project, designed for beginners, or those who have not previously encountered homekit
https://github.com/alpr777/homekit
perhaps an interesting transfer to your project or add in "projects which use"

thanks for your work!! 👍🏻

**Comment by brutella** [comment]
FYI I've refactored hc and made a new library out of it called. 

The new implementation is much more simpler. The new library is available as [hap](https://github.com/brutella/hap).
