### ISSUE TITLE
Expose `http.ServeMux` to allow applications to add additional endpoints

### ISSUE THREAD

**Issue by benpye** [brutella/hc#212]
It would be useful to expose the `http.ServeMux` so an application could add an additional listener without needing to listen on a new port. In my case I want to expose a Prometheus metric endpoint, currently I need to listen on an additional point but I don't think there is any reason this should be necessary.

**Comment by brutella** [comment]
I've refactored hc and made a new library out of it. The new library is available as [hap](https://github.com/brutella/hap).
The new hap server gives you access to the [ServeMux](https://pkg.go.dev/github.com/brutella/hap#Server.ServeMux).
