### ISSUE TITLE
Radiation sensor

### ISSUE THREAD

**Issue by sighmon** [brutella/hc#213]
Hi @brutella,

I've been playing around trying to setup a [DF Robot Gravity Geiger Counter](https://www.dfrobot.com/product-2547.html) in HomeKit with `hc` ([via a Prometheus exporter](https://github.com/sighmon/geiger_counter_df_robot_sen0463_esp32_http_server)).

My repo: https://github.com/sighmon/homekit-geiger-counter

In the `Home` app it reports `This accessory is not currently supported by the Home app`.

I assume the [TypeGeigerCounter UUID](https://github.com/sighmon/homekit-geiger-counter/blob/main/geigercounter/geigercounter.go#L24) I made up is causing the problem, or perhaps the [TypeRadiation UUID](https://github.com/sighmon/homekit-geiger-counter/blob/main/geigercounter/radiation.go#L8)?

Do you know which UUIDs I should be using? Anything else I have messed up?

<img src="https://user-images.githubusercontent.com/314298/158135530-d7e43f76-22e6-426a-b172-7d64e73f41cc.png" width=25% />

**Comment by brutella** [comment]
> I assume the [TypeGeigerCounter UUID](https://github.com/sighmon/homekit-geiger-counter/blob/main/geigercounter/geigercounter.go#L24) I made up is causing the problem, or perhaps the [TypeRadiation UUID](https://github.com/sighmon/homekit-geiger-counter/blob/main/geigercounter/radiation.go#L8)?

You are right, those types are not known to the Apple Home app, and therefore not supported. But other HomeKit apps (ex. [Home+](https://itunes.apple.com/us/app/home-smart-home-automation/id995994352)) would display the custom types correctly.

**Comment by sighmon** [comment]
@brutella I checked `Home+` too, but I can't find it in any of the categories. Should it appear in `Sensors` seeing I'm setting the type to [TypeSensor](https://github.com/sighmon/homekit-geiger-counter/blob/main/geigercounter/geigercounter.go#L16)?

**Comment by sighmon** [comment]
@brutella Any chance you've had the time to have a look at why my sensor isn't showing up in `Home+`?

**Comment by brutella** [comment]
I've just checked out your project and I've found an issue where you use the same type for all 3 radiation characteristics. HomeKit doesn't seem to like that and returns an error. Make sure that every characteristic in the radiation service has a different type.

Secondly I've updated Home+ to support your accessory as a sensor. Please install the latest [TestFlight build](https://testflight.apple.com/join/IrqVh5c3) and try it again.

**Comment by sighmon** [comment]
@brutella Do you expect this to work for the 3 radiation characteristics? https://github.com/sighmon/homekit-geiger-counter/pull/3/files

Your TestFlight build of Home+ works perfectly thank you!

<img src="https://user-images.githubusercontent.com/314298/165075948-2e908f80-951e-4161-beb3-c257bc05bf51.png" width=25% />
