### ISSUE TITLE
Clarify on project pages that this is not opensource

### ISSUE THREAD

**Issue by kapilt** [brutella/hc#24]
Given the license does not comply with OSI definition, Its probably disingenuous to advertise it as opensource given its constraints. 

http://opensource.org/osd

**Comment by kapilt** [comment]
As an example "HomeControl is open source and available on Github." is what it says on 
https://selfcoded.com/homecontrol

**Comment by brutella** [comment]
Fixed

**Comment by thomersch** [comment]
Sorry for hijacking the issue, but may I ask why you chose this restrictive license? I would like to put a BSD/MIT license on my derived projects which is impossible with such license terms.
