### ISSUE TITLE
High latency client can crash the bridge

### ISSUE THREAD

**Issue by bwdezend** [brutella/hc#25]
If the client is under enough packet loss or experiencing high enough latency, the following happens to me:

2015/07/18 19:28:44 [ERRO] Decryption failed: read tcp 192.168.1.104:65302: operation timed out
2015/07/18 19:28:44 [ERRO] Decryption failed: use of closed network connection
2015/07/18 19:28:44 [INFO] Close connection and remove session

The server is then dead and must be halted and resumed. If this is a fatal error, it should be handled as such and the program should terminate. If not, the connection should be retried. I haven't gotten deep enough into netio to see where to handle this better, and this is my first real foray into reading someone else's go.

**Comment by bwdezend** [comment]
More specifically - when my iOS device leaves the WiFi network and rejoins, it appears the encrypted session is not properly re-neogtiated and left open. I can easily reproduce this by:

   1: Checking the state of a device on my bridge
   2: Turning WiFi off on my iOS device
   3: Checking the state (which is now Unreachable)
   4: Turning WiFi back on
   5: Checking the state a 3rd time.

**Comment by brutella** [comment]
HomeKit on iOS leaves the TCP connection open as long as possible. When the connection is left open and not closed, the next read on the socket fails. The library then closes the connection and prints out the error to the console. The server is NOT dead at this point and still waits for new connections. 

It seems to me an iOS bug when the connection is left open when the device leaves the network. I don't know how to fix that on the server side. Any ideas?

**Comment by bwdezend** [comment]
The iOS client takes a long time to renegotiate a connection after one of these idle connection timeouts occur. After testing this weekend, it will eventually reconnect, but it often takes 10+ attempts over 30 or 45 minutes to be able to re-establish. I agree this smells like an iOS bug.

Stopping and restarting the server seems to be the only way I can ensure a quick restoration of services. I'll keep looking and see if I can find a way to mitigate this timeout.

**Comment by mxlje** [comment]
@bwdezend I am seeing the same behavior, but even after restarting the accessory (I am experimenting with https://github.com/brutella/hklight), I can’t get my phone to reconnect. Do you have any new information on this?

I’m still relatively new to HomeKit and `hc`, but I really like the prospects of creating my own "devices" in Go.

**Comment by bwdezend** [comment]
I had to suspend work on HomeKit hacking due to time constraints. Sadly, I have nothing new to share. There's also a chance that iOS9 has yet again changed things.

**Comment by mxlje** [comment]
Ok, thanks for the quick reply. Yes, could very well be the case, that HomeKit is kinda buggy with iOS9.

**Comment by kevinduterne** [comment]
Is this also causing the connection to become "not reachable" after any connection loss of the IOS device? 5 to 10 min after adding the Homekit bridge it will become unavailable in the Home app.. 
On the server I am seeing :
[INFO] Close connection and remove session
Then i have to repair before I can use it again.. 
Is there anything to do about this?

**Comment by brutella** [comment]
@kevinduterne This should already be fixed. Please get the latest changes from the master branch and try it again.

**Comment by kevinduterne** [comment]
Correct, get fixed the issue! Thx

**Comment by brutella** [comment]
Is this still an issue?

**Comment by kevinduterne** [comment]
No It has been resolved

**Comment by bwdezend** [comment]
With current code from master, I can also confirm that this is no longer an issue with iOS 9.3.1.

**Comment by brutella** [comment]
Thanks
