### ISSUE TITLE
Q: Did somebody create a Dockerfile for Homecontrol already? n/t

### ISSUE THREAD

**Issue by tiptronic** [brutella/hc#32]
Q: Did somebody create a Dockerfile for Homecontrol already? n/t

**Comment by brutella** [comment]
No because I don't have experience with Docker.
Why would we need that?

**Comment by tiptronic** [comment]
Using Docker we could spin up a couple of HomeControl devices with close to no effort, making it easy to check out the various components it has to offer. (It's also very portable and therefor great for development)

**Comment by tiptronic** [comment]
I mean: for noobs to GO (like me), stepping in is much easier, since using Docker you can quickly spawn a little VM with all dependencies already in place and start with the fun part of hc ;)

**Comment by brutella** [comment]
Sounds interesting – feel free to work on that. 😉

**Comment by olvesh** [comment]
hc is just the framework, right? So it does not make sense to start hc by itself.
Dockerfiles should be added to the implementations, e.g hklight and friends.

**Comment by juliancheal** [comment]
I've got a Dockerfile running a Homecontrol power switch. Just having issues with networking. 🤔 I think it's the mDNS that I haven't quiet yet configured my Docker image correctly with.

Anyway once that's all working, I'll link back to here. :)

**Comment by sgrimee** [comment]
@juliancheal try maybe `docker run --net=host`. There may be a way to get mDNS to work without it, but as a test it could help. Not that if you are on a mac or windows the host will be the virtual machine docker is running on. On a linux box however it should work directly.

**Comment by dj95** [comment]
I created a Dockerfile for my homekit project with this awesome package. If you use it with `--net=host`, as @sgrimee suggests, it works like a charm.

https://gist.github.com/dj95/66a4066a7d207ad77f969383f60f5509
