### ISSUE TITLE
bonjour fail... help

### ISSUE THREAD

**Issue by toshakluev** [brutella/hc#36]
Hi, folks,

i try to start the example from the tutorial of brutella but i receive an error:

antonkluev.pi ~/go/src/hklight $ go run hklightd.go
2015/10/26 21:18:07 [INFO] Accessory IP is 192.168.1.8
2015/10/26 21:18:07 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: address family not supported by protocol

the homekit apps don't see my virtual accessoire..
can anyone help me? 

and i have one more question: can i use my raspberry pi to control multiple accessoires?
thx guys!

**Comment by brutella** [comment]
This is not a real error. 
The mDNS record should still be visible over IPv4.
