### ISSUE TITLE
Thermostat regularly won't connect through Home app

### ISSUE THREAD

**Issue by tomtaylor** [brutella/hc#39]
I've got a thermostat that I'm driving with your Home app. Using iOS 9 it's regularly unreachable, unless I restart the Go application. Can I help provide any diagnostics, Wireshark traces, etc?

**Comment by bmurray** [comment]
Same issue here. I've only started debugging mine, but it seems to start out with a deluge of decryption issues:

[ERRO] Decryption failed: read tcp ... read: connection reset by peer
[ERRO] Decryption failed: read tcp ... use of closed network connection

**Comment by brutella** [comment]
Are you using the latest version of the library?
Do you have iOS 9.1 installed?

**Comment by tomtaylor** [comment]
@brutella pretty close, I'm currently using d8b549614c67067fc17f3bb565692789d7d9fc6d, and yeah I'm using 9.1.

**Comment by brutella** [comment]
@tomtaylor Can you please provide the steps, which lead to this problem – or do you have a sample project?

**Comment by tomtaylor** [comment]
Sure - the code is over here: https://github.com/tomtaylor/heating.

**Comment by tomtaylor** [comment]
I *think* that compiling it with `GOARM=5` might have fixed this, as mentioned in #31.

**Comment by brutella** [comment]
@tomtaylor Is the issue fixed now?

**Comment by tomtaylor** [comment]
Yes, I think so, thanks a lot.
