### ISSUE TITLE
MFi Compatibility

### ISSUE THREAD

**Issue by oransel** [brutella/hc#40]
How can you enable the MFi compatibility? Is there stub functions to fill?

**Comment by brutella** [comment]
MFi compatibility requires a special chip – you have to be MFi member to get access to it. https://mfi.apple.com

There is nothing we can do in software to be MFi compatible.

**Comment by oransel** [comment]
Thank you for responding. I have development board with the MFi chip attached on a i2c bus and the necessary documentation for the datamap. I was wondering if you could help me figure out where to put in your code the responses from the chip. As far as I understand, it needs to be a challenge response type of exchange.

**Comment by brutella** [comment]
We should not discuss this in public. Please get in touch via email matthias.hochgatterer@gmail.com
