### ISSUE TITLE
Invalid characteristic found when using HomeKit and AppleTV for remote access

### ISSUE THREAD

**Issue by ablyler** [brutella/hc#43]
When I attempt to use HomeKit + hk from outside my home network I see the following warning: `No characteristic found with aid 0 and iid 0`.  This appears to be preventing me from getting details about the device behind hk as well.

**Comment by brutella** [comment]
Did you try to re-pair the HomeKit bridge in your iOS HomeKit app and try again?

**Comment by ablyler** [comment]
Yeah, tried that. Still get the errors. I can get and set the temp, but the details do not show up.

**Comment by brutella** [comment]
Which iOS and Apple TV version are you using?

**Comment by ablyler** [comment]
iOS 9.2 and tvOS 9.1

**Comment by tjbx** [comment]
I'm seeing this as well. Same versions of everything.

**Comment by myhalici** [comment]
Same for me

**Comment by brutella** [comment]
Could anyone reproduce this issue?

**Comment by brutella** [comment]
This should be fixed now
