### ISSUE TITLE
Control of the IP Address that HC binds to

### ISSUE THREAD

**Issue by tjbx** [brutella/hc#45]
It would be nice to be able to control which ip address HC binds to instead of it just choosing one as it does now. I run HC on my linux gateway/firewall system and it was grabbing the outside interface address when I prefer it to keep its traffic on my internal net.

I've got a diff for the GetFirstLocalIPAddress func in mdns.go that first attempts to use the hostname ip address before falling back to just blindly grabbing the first available IP address. 

An even better solution would be to be able to specify the address to bind to, perhaps as an additional variable in hap.Config? I don't "know" go but have figured it out enough for this diff. If hap.Config would be an approved method, I could work on implementing that.

**Comment by brutella** [comment]
Go ahead, looking forward to your pr 🙂

**Comment by tjbx** [comment]
I've no experience with the whole git thing. Here is a diff for the above mentioned GetFirstLocalIPAddress func.

[mdns.hostname.diff.txt](https://github.com/brutella/hc/files/99134/mdns.hostname.diff.txt)

Since the hap.Config solution is more involved, it will take a while longer.

**Comment by brutella** [comment]
Please check if commit 82a77ed resolves this issue

**Comment by tjbx** [comment]
Seems to work for me though it might be nicer to be able to specify the ip address as a string in the config (like all the other config vars) and then convert it in code with net.ParseIP. The fix for the "Invalid characteristic found when using HomeKit and AppleTV for remote access #43" also seems to work great. Thanks much.

**Comment by tjbx** [comment]
Sorry for the slow reply - sometimes I get updates from github via email and other times I only see them when I visit this webpage. Anyhow, I tried it and the IP as string seems to work as expected. One last(?) request would be to somewhere still have the 

log.Println("[INFO] Accessory IP is", ip) 

that used to be in "func (s *MDNSService) Publish() error" of hap/mdns.go 

just as a sanity check to make sure the ip address you specify is the one being used. Not completely necessary but could be helpful in debugging.

**Comment by tjbx** [comment]
Works as desired. Thanks.

**Comment by brutella** [comment]
Fixed with d8c223d
