### ISSUE TITLE
Cannot pair if model.Info.Name contains a space 

### ISSUE THREAD

**Issue by yene** [brutella/hc#48]
Cannot pair if model.Info.Name contains a space.

Steps:
* clone hklight
* change "Lamp" to "Lamp 2"
* try to pair

**Comment by marconett** [comment]
running into the same issue with an unchanged hklight clone. the home ios app gives the error "client request error when communicating with accessory" when trying to pair.

**Comment by yene** [comment]
Go 1.6 does validate the host name in HTTP requests, which HomeKit uses for the accessory name.

https://github.com/golang/go/commit/6e11f45ebdbc7b0ee1367c80ea0a0c0ec52d6db5#diff-bf538ad0b0c9263061db13ca6d8f324eR708

**Comment by brutella** [comment]
iOS encodes whitespaces in the host header field value as `\032`. HTTP/1.1 does not allow backslash characters in the host header field value – Go1.6 checks for valid host names.

I've filed a [radar](http://openradar.appspot.com/radar?id=4931940373233664) for Apple to fix that.
I will add a workaround to hc soon.
