### ISSUE TITLE
Add fan, garage door opener, lock management and mechanism accessory types

### ISSUE THREAD

**Issue by brutella** [brutella/hc#5]

**Comment by ipstatic** [comment]
Any eta on getting garage door support?

**Comment by brutella** [comment]
Pull request for this would be great.

**Comment by elliots** [comment]
These are described in /model/metadata-dump_iOS8.3.txt, is there a newer version from iOS9?

**Comment by brutella** [comment]
I've just added the new characteristic and service types used in iOS 9. You can find the metadata plist file in *model/metadata_iOS9.plist*

**Comment by brutella** [comment]
All services and characteristics from iOS 9 are now available since v0.1.0.
