### ISSUE TITLE
Fix bug where iOS closes the connection when mDNS name contains "ö" character

### ISSUE THREAD

**Issue by brutella** [brutella/hc#51]
Issue is discussed [here](https://github.com/brutella/hklifx/issues/16)

**Comment by fpg1503** [comment]
Same thing for `â` :/

**Comment by daenney** [comment]
It seems to be the same thing for anything with a diacritic mark. As long as you stick to Latin-1 everything works.

**Comment by brutella** [comment]
Right, HomeKit uses the published mDNS name in the http host header field. 
50499bea12ffc2d396ddb3e9015669ec81f7f588 now automatically removes accent characters from the mDNS service name.
