### ISSUE TITLE
Bonjour: Failed to handle query

### ISSUE THREAD

**Issue by st3fan** [brutella/hc#55]
When I start up my app that runs two accessories, I get the following right at startup:

```
2016/08/16 22:26:09 [ERR] bonjour: Failed to handle query:
  write udp4 0.0.0.0:5353->192.168.0.16:5353:
    sendto: operation not permitted
```

I am running on *Ubuntu 16.04* and I have stopped `avahi-daemon` to make sure port `5353` is available.

Is the problem here that it is trying to send a UDP packet from `0.0.0.0` ?

**Comment by st3fan** [comment]
Probably answering my own question .. if I configure the IP address to which to bind, the error goes away:

```
config := hc.Config{
    Pin: "11122333",
    IP:  "192.168.0.254",
}
```

I wonder if this happens because I have multiple network interfaces configured on the host.

**Comment by brutella** [comment]
Should be fixed now, thanks for reporting.
