### ISSUE TITLE
Additions/modifications

### ISSUE THREAD

**Issue by mikejac** [brutella/hc#56]
Hi Matthias,

First, this is not an issue as such :-)

Second, great work you have done here. Now then, I'm working on an "HomeKit to MQTT Server" that allow bidirectional communication between HomeKit (using your HomeControl) and devices communicating via the MQTT protocol. So far I've made a new transport based on
'ip_transport.go' and a few additions/modifications here and there (including adding new accessories).

So the question is: are you willing to accept PRs (if the code is ok of course)?

If I commit/sync to github you can have a look - any interest?

/michael

**Comment by brutella** [comment]
This library is only about the HomeKit Accessory Protocol. You should make a separate repository because your additions are related to a different protocol.

**Comment by mikejac** [comment]
Perhaps I didn't explain it well enough: The other protocol, MQTT, is not
part of "my" updates/additions - that takes place outside HC. It's only HAP
but I had to re-arrange some code to get things such as "auto-discovery" to
work.

/michael

2016-09-05 9:41 GMT+02:00 Matthias <notifications@github.com>:

**Comment by brutella** [comment]
Lets make pull requests and discuss your changes there.
