### ISSUE TITLE
No temperature characteristic for Lightbulb

### ISSUE THREAD

**Issue by sanghviharshit** [brutella/hc#61]
iOS 10 has support for setting temperature (Kelvin). But I noticed that service/lightbulb.go doesn't include temperature characteristic.

**Comment by brutella** [comment]
HomeKit doesn't support color temperatures. You should use the hue, saturation and brightness characteristics to get specific color temperatures.

**Comment by JWo1F** [comment]
@brutella, you need to reopen this issue. Because HomeKIt support Color Temperature now.

UUID: 000000CE-0000-1000-8000-0026BB765291
HomeBridge example: [the linklink](https://developers.homebridge.io/#/characteristic/ColorTemperature)
