### ISSUE TITLE
New accessories

### ISSUE THREAD

**Issue by xxcombat** [brutella/hc#62]
Thanks for your work!
You plan to add new accessories?
Very interested in the camera and doorbell.

**Comment by brutella** [comment]
The doorbell service is already available in [service/doorbell.go](https://github.com/brutella/hc/blob/master/service/doorbell.go). IP-camera is also available but there is currently no hookup to a camera stream (like from ffmpeg).

**Comment by brutella** [comment]
Closed due to inactivity
