### ISSUE TITLE
Q: Is it possible to query the state of other accessories through hc?

### ISSUE THREAD

**Issue by olvesh** [brutella/hc#65]
If I have other HomeKit enabled devices, would it be possible to query the state of those, and build new aggregated services from those devices? 

Say I want to create a thermostat using the the already HomeKit connected temperature sensor in Elgato Eve Room, would that be possible via HomeKit or would I have to get data from the Bluetooth transfer directly?

**Comment by brutella** [comment]
No, HomeKit accessories don't know anything about other accessories.
