### ISSUE TITLE
Problem with local interfaces on windows an wifi

### ISSUE THREAD

**Issue by CristianMori** [brutella/hc#67]
the getFirstLocalIPAddr() on my machine returned the ip of the Microsoft Windows Virtual WiFi that, despite it being a disabled interface, was reporting an ip address of 169.x.x.x
Had to work around by checking that the address of the ip was not in the 169 range

**Comment by brutella** [comment]
You can manually set the IP address of the server by using the `IP` property of the `Config` struct.

See https://github.com/brutella/hc/blob/master/config.go#L25
