### ISSUE TITLE
Reset accessory

### ISSUE THREAD

**Issue by WingedToaster** [brutella/hc#68]
I was having issues with the accessory so I unpaired it with my Home app. Now I can't seem to pair it again, is there a way to reset the whole accessory back to 'factory' so it allows it to be discoverable? The logs just say 
```
INFO 2017/01/07 14:17:17 Accessory IP is 10.0.xxx.xxx
```

**Comment by WingedToaster** [comment]
Figured it out somewhat...
I went into the working directory and then the directory with the accessory name then deleted all the files and restarted the accessory app. This allowed the accessory to be discoverable again but it's still not getting paired. Are there other files that need to be deleted or reset?

**Comment by brutella** [comment]
> Are there other files that need to be deleted or reset?

No, the program stores configuration data and crypto keys into that folder.  Deleting that files will reset the program.
