### ISSUE TITLE
Switch state via HTTP

### ISSUE THREAD

**Issue by TribuneX** [brutella/hc#69]
Hello,

I want to include a sensor accessory, which tells me if I am at home. Do you have a suggestion on how to enable an HTTP API within an accessory, which will be called once I enter or exit a location via an HTTP POST? 

Thanks!

**Comment by brutella** [comment]
If you want to change the state of a switch using HTTP Post, you should setup a HTTP server and set the On characteristic value in the handler.

```go
http.HandleFunc("/turnOn", func(w http.ResponseWriter, r *http.Request) {
    acc.Switch.On.SetValue(true)
})
```

**Comment by brutella** [comment]
Close due to inactivity

**Comment by mkrcek** [comment]
Hi @brutella 
I wanted to try it, but I am not sure how to do it correct way.
I added this code to your example (to function main), but when I call http://localhost:9090/turnOn 
i get only this message "could not get any response."

====

`
http.HandleFunc("/turnOn", func(w http.ResponseWriter, r *http.Request) {
    acc.Switch.On.SetValue(true)
})
....

hc.OnTermination(func() {
		t.Stop()
})
t.Start()

http.ListenAndServe(":9090", nil) // set listen port

`

**Comment by mkrcek** [comment]
you are right. So how can I use it? If I put 
  http.ListenAndServe(":9090", nil) 
befor 
  t.Start()
HK never starts, right? Do you have any example?

**Comment by brutella** [comment]
Here is an example on how to do that.
https://gist.github.com/brutella/e5bb4be15f2c78e42050e3cf24b0504c

**Comment by mkrcek** [comment]
Great. It works perfect!! Thanks
