### ISSUE TITLE
Colour setting in iOS HomeKit 

### ISSUE THREAD

**Issue by danward79** [brutella/hc#71]
Hi @brutella,

I've been generating a bridge for my Wemo devices, bulbs, switches, etc. All working well.

For the bulbs I am using `accessory.NewLightbulb(i)`. The physical bulbs do not have the ability to set colour, they only have the ability to change brightness. 

In iOS, there is an option to set colour, which is obviously invalid in this case. Is there a way to prevent this option from appearing? Is appearing because of the characteristics set in lightbulb?

I tried setting: `acc.Lightbulb.Saturation = nil` and `acc.Lightbulb.Hue = nil` after I created the accessory.

Wondering if this is an iOS feature.

It would be nice to solve without making a new accessory.

Thanks

**Comment by brutella** [comment]
When you look a the [lightbulb](https://github.com/brutella/hc/blob/master/service/lightbulb.go#L10-L17) service, you see that it has a saturation and hue characteristic. Those characteristics define the color. If you don't want to have a color, just define a custom service like this
```go
type CustomLightbulb struct {
	*service.Service

	On         *characteristic.On
	Brightness *characteristic.Brightness
}

func NewCustomLightbulb() * CustomLightbulb {
	svc := service.Lightbulb{}
	svc.Service = service.New(service.TypeLightbulb)

	svc.On = characteristic.NewOn()
	svc.AddCharacteristic(svc.On.Characteristic)

	svc.Brightness = characteristic.NewBrightness()
	svc.AddCharacteristic(svc.Brightness.Characteristic)

	return &svc
}
```

**Comment by danward79** [comment]
Would you accept a pull request for a Wemobulb?
