### ISSUE TITLE
How to make Brifge Accessory?

### ISSUE THREAD

**Issue by reejinbouk** [brutella/hc#72]
Hello, I'm trying to add some accessories as one Bridge

Should I use Container?

This example not works for me:

switchInfo := accessory.Info{
		Name: "Switch",
	}
	lampInfo := accessory.Info{
		Name: "Lamp",
	}
	acc := accessory.NewSwitch(switchInfo)
	acc2 := accessory.NewLightbulb(lampInfo)

	container := accessory.NewContainer()
	container.AddAccessory(acc.Accessory)
	container.AddAccessory(acc2.Accessory)

	config := hc.Config{Pin: "12344321", Port: "12345", StoragePath: "./db"}
	t, err := hc.NewIPTransport(config, container.Accessories[])

	if err != nil {
		log.Info.Panic(err)
	}

**Comment by brutella** [comment]
Please refer to the code documentation of [func NewIPTransport()](https://github.com/brutella/hc/blob/master/ip_transport.go#L45-L46)

This should work

`t, err := hc.NewIPTransport(config, acc.Accessoory, acc2.Accessory)`

**Comment by reejinbouk** [comment]
hello, 
but is there a way to add it like slice?
if I don't know quantity of accessories and I will load it from config - I can't use this:
t, err := hc.NewIPTransport(config, acc.Accessoory, acc2.Accessory)

it should be like:
t, err := hc.NewIPTransport(config, bridge, acc[].Accessory)

**Comment by brutella** [comment]
You need an `[]*accessory.Accessory` array. For example

```go
var accessories []*accessory.Accessory = ...
hc.NewIPTransport(config, accessories...)
```

**Comment by p000** [comment]
When I append Accessory to array Its not adding. Also I'm trying to create the bridge dynamically with some of the lights and sensors which are in my database. I think there is a problem with this approach.

**Comment by brutella** [comment]
@p000 I wouldn't recommend adding accessory to a bridge dynamically. In this case I would create separate accessory for every light and sensor, similar to how I've done it  in [hklfix](https://github.com/brutella/hklifx/blob/master/hklifxd.go#L128)
