### ISSUE TITLE
Go 1.8 error

### ISSUE THREAD

**Issue by reejinbouk** [brutella/hc#75]
Updated to Go 1.8 and in pairing got Error on iPhone (Could not communicate)
Back to Go 1.7.1 and all works good.
Debug shows this errors:

DEBUG 2017/02/25 20:48:46 Setup secure session
DEBUG 2017/02/25 20:48:46 192.168.1.50:50142 GET /accessories
DEBUG 2017/02/25 20:48:46 {"accessories":[{"aid":1,"services":[{"iid":1,"type":"3E","characteristics":[{"iid":2,"type":"14","perms":["pw"],"format":"bool"},{"iid":3,"type":"20","perms":["pr"],"value":"undefined","format":"string"},{"iid":4,"type":"21","perms":["pr"],"value":"undefined","format":"string"},{"iid":5,"type":"23","perms":["pr"],"value":"Lamp","format":"string"},{"iid":6,"type":"30","perms":["pr"],"value":"undefined","format":"string"}]},{"iid":7,"type":"49","characteristics":[{"iid":8,"type":"25","perms":["pr","pw","ev"],"value":false,"format":"bool"}]}]}]}
DEBUG 2017/02/25 20:48:46 Decryption failed: read tcp 192.168.1.59:12345->192.168.1.50:50142: i/o timeout
DEBUG 2017/02/25 20:48:46 Decryption failed: read tcp 192.168.1.59:12345->192.168.1.50:50142: use of closed network connection
DEBUG 2017/02/25 20:48:46 Close connection and remove session

**Comment by Mumakil** [comment]
Same issue here. Go 1.8 results in the decryption failed messages and Go 1.7.5 works fine. For me the pairing step (up to pin input) works fine, but then when seeing the device details after pairing I get an error that the accessory cannot be found.

**Comment by brutella** [comment]
Fixed with 9eb86c3
