### ISSUE TITLE
remote support

### ISSUE THREAD

**Issue by tcurdt** [brutella/hc#80]
Is there any information about the remote setup (which usually is meant to be done via Apple TV)?
So basically reaching the accessory from outside of the home network.

**Comment by brutella** [comment]
If the Apple TV is connected to the same network as the HomeKit accessory, it will be automatically available via remote access. You have to make sure to sign in to iCloud on your Apple TV.

**Comment by tcurdt** [comment]
I was hoping to get around having an Apple TV for just this.
