### ISSUE TITLE
Add accessory at runtime

### ISSUE THREAD

**Issue by daenney** [brutella/hc#87]
I was wondering if it's possible to add new accessories at runtime, so when the IPTransport is already up.

I have a system that detects new compatible devices in my network that could be bridged to HomeKit so I'd like to just add those to the bridge without needing to restart the whole thing. Unfortunately `addAccessory` is not exported so I can't call that.

**Comment by daenney** [comment]
I suppose what I can do is copy the `ip_transport` and change it so that I have an exported `AddAccessory()` instead of an unexported one.

Slightly related question, if I would expose a `RemoveAccessory()` too, would it be enough to simply call `container.RemoveAccessory()` or do I need to do something more?

**Comment by brutella** [comment]
I wouldn't recommend changing accessories in an ip transport. Mainly because iOS will forget all customisation you made to an accessory (e.g. renaming it or moving it into a room) if you remove it from the ip transport. The next time you add it again, you will have to customise it again. This is annoying if a device is temporarily available.

What I do in the [hklifx](https://github.com/brutella/hklifx) project, is to create a new ip transport for every device. This way if a device is not available, the ip transport is not created and therefore the accessory is not reachable for HomeKit.

**Comment by daenney** [comment]
> I wouldn't recommend changing accessories in an ip transport. Mainly because iOS will forget all customisation you made to an accessory (e.g. renaming it or moving it into a room) if you remove it from the ip transport. The next time you add it again, you will have to customise it again. This is annoying if a device is temporarily available.

Argh. I had no idea that would happen. Most definitely less than ideal.

> What I do in the hklifx project, is to create a new ip transport for every device. This way if a device is not available, the ip transport is not created and therefore the accessory is not reachable for HomeKit.

That seems entirely feasible, though I suppose you then have to pair every accessory the first time? Seems that this would also easily support the more dynamic nature I'm looking for, as I could just destroy the transport if the device goes offline.

**Comment by brutella** [comment]
> Would it matter at all if the port of the associated transport would change?

No, only the name of the accessory has to be the same. If you set a different name, the accessory will get a new internal id and will look like a new device to HomeKit.

**Comment by daenney** [comment]
Awesome, then I have a way to solve my problem. Thank you very much for your advice, and home control!

**Comment by 172478394** [comment]
@daenney I have the same problem. How did you solve it?

**Comment by daenney** [comment]
@172478394 Did two things:

* In my case I'm mapping MQTT "topics" to HomeKit devices. Since topics are unique (only one device can be on the same topic, otherwise weirdness), we hash the topic name with a sha256. This gives us the `aid` and use that instead of the one hc generates. This guarantees we don't ever have aid collisions, which then makes it safe to add/remove devices
* We reimplemented part of `ip_transport` that gets embedded in our HomeKit bridge device. Whenever AddAccessorry/RemoveAccessorry gets called on the bridge we call the `updateConfig()` on `ip_transport`.

**Comment by SenH** [comment]
@daenney Is the MQTT to HomeKit bridge source available? Looking for something similar.
