### ISSUE TITLE
How to catch Read request?

### ISSUE THREAD

**Issue by reejinbouk** [brutella/hc#90]
Hello,
Please, how to catch Read value request from iOS to device?
thank you

**Comment by reejinbouk** [comment]
I found "GET characteristic" log at HAP section.
How can I catch this event?
Thank you.

**Comment by reejinbouk** [comment]
Hello, any advice about catch "get request"? 
Thank you

**Comment by timoschilling** [comment]
Why do you want to catch this request?

**Comment by reejinbouk** [comment]
when I start Home App, it request statuses. Then I catch this request and make request to hardware and return actual statuses.

**Comment by timoschilling** [comment]
HC didn't provide an interface to do that.

You should have an Interval in your app which pulls the value from your Hardware and set it as the current value in HC. Or your hardware should push on a change his current value to a interface MQTT or HTTP Server which gives the value into HC.

**Comment by timoschilling** [comment]
Here is an example of one off my apps, which pulls the state from a thermostat bright and set the current temp on the related HC termostat
https://github.com/timoschilling/fritzbridge/blob/master/fritzbridge.go#L73

**Comment by reejinbouk** [comment]
Thank you!
