### ISSUE TITLE
No Response 

### ISSUE THREAD

**Issue by tjbx** [brutella/hc#94]
I've got an X10 bridge I wrote, modified from edc1591/gohome, which has been working right along until iOS 11. After iOS11, homekit wouldn't see my bridge anymore. I ended up removing and re-adding it from homekit and things worked better but not great. Basically my bridge would become periodically unresponsive for no apparent reason.  So today, I updated to hc master in hopes things would be better since it seems to have new mdns code. What I'm experiencing now is that within about 30 seconds of starting, my bridge disappears and is I get "No Response". Seems to work fine for those 30 seconds and then no response. Since others seemed to be having problems with special characters, I tried changing mine from "X10 Bridge" to "X10.Bridge" to "X10-Bridge" but it didn't help. Also the "." seemed to get replaced with an "_" in that test. Here's what I see scanning for hap mdns entries:

solyaris> dns-sd -B _hap._tcp
Browsing for _hap._tcp
DATE: ---Thu 19 Oct 2017---
13:40:25.983  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
13:41:19.019  Add        2  13 local.               _hap._tcp.           X10_Bridge
13:41:45.775  Rmv        0  13 local.               _hap._tcp.           X10_Bridge
13:46:10.267  Add        2  13 local.               _hap._tcp.           X10_Bridge
13:46:42.954  Rmv        0  13 local.               _hap._tcp.           X10_Bridge
14:09:05.208  Add        2  13 local.               _hap._tcp.           X10_Bridge
14:09:33.415  Rmv        0  13 local.               _hap._tcp.           X10_Bridge
14:13:50.605  Add        2  13 local.               _hap._tcp.           X10_Bridge
14:14:24.253  Rmv        0  13 local.               _hap._tcp.           X10_Bridge
14:15:35.356  Add        2  13 local.               _hap._tcp.           X10_Bridge
14:17:14.464  Rmv        0  13 local.               _hap._tcp.           X10_Bridge
14:22:26.395  Add        2  13 local.               _hap._tcp.           X10_Bridge
14:23:06.355  Rmv        0  13 local.               _hap._tcp.           X10_Bridge
14:31:58.205  Add        2  13 local.               _hap._tcp.           X10_Bridge
14:32:29.270  Rmv        0  13 local.               _hap._tcp.           X10_Bridge
14:33:53.671  Add        2  13 local.               _hap._tcp.           X10_Bridge
14:34:24.412  Rmv        0  13 local.               _hap._tcp.           X10_Bridge
15:07:50.564  Add        2  13 local.               _hap._tcp.           X10_Bridge
15:08:19.210  Rmv        0  13 local.               _hap._tcp.           X10_Bridge
15:13:26.244  Add        2  13 local.               _hap._tcp.           X10-Bridge
15:13:44.775  Rmv        0  13 local.               _hap._tcp.           X10-Bridge

I'm not clear on how this all ties together but any help appreciated.

**Comment by brutella** [comment]
Please enable debug logging in hc with `log.Debug.Enable()` (don't forget to import `"github.com/brutella/hc/log"`) and attach your log.

**Comment by tjbx** [comment]
The log doesn't seem particularly useful in that when (according to dns-sd run in a different window) the mdns Rmv occurs, nothing is logged. Maybe something in there is meaningful to you?

Here's the dns-sd output for the time this log was created:

solyaris> dns-sd -B _hap._tcp
Browsing for _hap._tcp
DATE: ---Thu 19 Oct 2017---
19:18:29.370  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
19:18:40.264  Add        2  13 local.               _hap._tcp.           X10_Bridge
19:19:16.955  Rmv        0  13 local.               _hap._tcp.           X10_Bridge


[home.log](https://github.com/brutella/hc/files/1400304/home.log)

**Comment by tjbx** [comment]
I still have not had any luck getting this to work. I incorporated the slight changes from the example code (setting up the onTerminiation func) but it still stops working after 30 seconds, as soon as it disappears from the dns-sd listing. For reference, my normal host is an EL6 linux box running go 1.7.6. When I try to run the same on my Mac with High Sierra and a MacPorts installed go 1.9.1, it blows up in the mdns code:

solyaris> ../../../../bin/X10-BottleRocket-Bridge
panic: reflect: call of reflect.Value.Int on zero Value

goroutine 1 [running]:
reflect.Value.Int(0x0, 0x0, 0x0, 0x13e9df7)
	/opt/local/lib/go/src/reflect/value.go:908 +0x141
golang.org/x/net/ipv4.sysfd(0x15a7ac0, 0xc42000e048, 0xc42000e048, 0x15a7ac0, 0xc42000e048)
	/Users/tjb/goWorkspace/src/golang.org/x/net/ipv4/helper_unix.go:46 +0x196
golang.org/x/net/ipv4.(*payloadHandler).sysfd(0xc4200824d0, 0x15a7ac0, 0xc42000e048, 0xc4200824b0)
	/Users/tjb/goWorkspace/src/golang.org/x/net/ipv4/helper_unix.go:31 +0x5b
golang.org/x/net/ipv4.(*PacketConn).SetControlMessage(0xc4200824b0, 0x8, 0xc420082401, 0xc42000e048, 0x0)
	/Users/tjb/goWorkspace/src/golang.org/x/net/ipv4/endpoint.go:55 +0x4c
github.com/brutella/hc/vendor/github.com/brutella/dnssd.newMDNSConn(0x10, 0x0, 0x0)
	/Users/tjb/goWorkspace/src/github.com/brutella/hc/vendor/github.com/brutella/dnssd/mdns.go:105 +0x5f2
github.com/brutella/hc/vendor/github.com/brutella/dnssd.NewResponder(0x13ea972, 0x8, 0xc420014800, 0x10)
	/Users/tjb/goWorkspace/src/github.com/brutella/hc/vendor/github.com/brutella/dnssd/responder.go:40 +0x26
github.com/brutella/hc/vendor/github.com/brutella/dnssd.init()
	/Users/tjb/goWorkspace/src/github.com/brutella/hc/vendor/github.com/brutella/dnssd/responder.go:37 +0x198
github.com/brutella/hc.init()
	<autogenerated>:1 +0x7f
main.init()
	<autogenerated>:1 +0x49
solyaris>

**Comment by tjbx** [comment]
Could someone with a working environment please post details. Base OS version, GO version, etc. High Sierra/GO 1.9.2 blows up in the mdns code like in the comment above.

**Comment by jkaflik** [comment]
@tjbx Same for me on High Sierra - after @brutella refactored mdns. I will try today with some ARM with armbian OS and let you know

**Comment by tjbx** [comment]
Any updates?

**Comment by jkaflik** [comment]
Sorry nowadays I have no time for my hc project. Will try to reach it in this week.

**Comment by brutella** [comment]
@tjbx Make sure that the package in `$GOPATH/src/golang.org/x/net` is up-to-date to resolve your crash.

**Comment by tjbx** [comment]
I thought 'go get' should have kept stuff up to date automatically but it appears it doesn't. On my High Sierra/go 1.9.2 test setup, removing src/golang.org/x/net and rerunning go get fixed the problem of the immediate crash. With that success in mind, on my EL6/go 1.7.6 normal setup, I blew away all of src to make sure everything was up to date and ran go get. That fixed all my problems - hap no longer disappears after 30 seconds when monitoring with "dns-sd -B _hap._tcp". In fact, everything seems much more responsive than ever before.

**Comment by brutella** [comment]
Great news. I think we can close the issue now.
