### ISSUE TITLE
Ctrl-C Deadlock

### ISSUE THREAD

**Issue by nickw444** [brutella/hc#95]
It appears upon quiting a bridge using ctrl-c, it appears to wait forever to quit.

Pinning to version 40cab825bcb1a8ae0cb198e25de2752d0804d85b appears to work as expected (CTRL-C ends the bridge process), however latest master is exhibiting this issue.

I am able to reproduce this with the [API Example](https://github.com/brutella/hc#api-example)

**Comment by nickw444** [comment]
(with that being said) New DNS library is looking great 👌

**Comment by timoschilling** [comment]
I have the same issue `CTRL-\` works for me to exit the process.

**Comment by nickw444** [comment]
Worth noting that supervisorctl seems to have no trouble gracefully stopping a running proc too

**Comment by brutella** [comment]
@nickw444 I'm not able to reproduce this issue using `_example/example.go`. It does work as expected for me.

What version of go are you using?

**Comment by timoschilling** [comment]
`CRTL-C` didn't work for me and I'm using `1.9.1`

**Comment by brutella** [comment]
Running from TextMate seems to kill the process after some time no matter what. Running from Terminal gave me the deadlock as well.

I've updated `_example/example.go` and readme on how to correctly stop an ip transport.

Calling `t.Stop()` returns a channel to wait until the HTTP server and mDNS responder stopped as well. If you don't read from that channel `t.Start()` never returns.

**Comment by timoschilling** [comment]
The fix works for me, THX

**Comment by nickw444** [comment]
Thanks for the fix 👍
